-- Dimenisones: tiempo, producto, cliente, evaluacion_servicio, contrato, estado_contrato, sucursal, siniestro
-- Hechos: metas, evaluacion_servicio, registro_servicio, resgistro_sinistro
DROP SCHEMA IF EXISTS SEGURO_DW_G26473741 CASCADE;

CREATE SCHEMA SEGURO_DW_G26473741;
--DIMENSIONES
CREATE TABLE SEGURO_DW_G26473741.DIM_TIEMPO(
  SK_DIM_TIEMPO INTEGER,
  COD_ANNIO INTEGER,
  COD_MES INTEGER,
  COD_DIA_ANNIO INTEGER,
  COD_DIA_MES INTEGER,
  COD_DIA_SEMANA INTEGER,
  COD_SEMANA INTEGER,
  DESC_DIA_SEMANA VARCHAR(10),
  DESC_DIA_SEMANA_CORTA VARCHAR(5),
  DESC_MES VARCHAR(20),
  DESC_MES_CORTA VARCHAR(3),
  DESC_TRIMESTRE INTEGER,
  DESC_SEMESTRE INTEGER,
  FECHA_COMPLETA DATE,
  CONSTRAINT PK_DIM_TIEMPO PRIMARY KEY (SK_DIM_TIEMPO)
);
CREATE TABLE SEGURO_DW_G26473741.DIM_PRODUCTO(
    SK_DIM_PRODUCTO INTEGER,
    COD_PRODUCTO INTEGER,
    NB_PRODUCTO VARCHAR(25),
    DESCRIP_PRODUCTO VARCHAR(25),
    COD_TIPO_PRODUCTO VARCHAR(25),
    NB_TIPO_PRODUCTO VARCHAR(25),
    CALIFICACION INTEGER,
    CONSTRAINT PK_DIM_PRODUCTO PRIMARY KEY (SK_DIM_PRODUCTO)
);

CREATE TABLE SEGURO_DW_G26473741.DIM_CLIENTE(
    SK_DIM_CLIENTE INTEGER,
    COD_CLIENTE INTEGER,
    NB_CLIENTE VARCHAR(25),
    CI_RIF VARCHAR(45),
    TELEFONO VARCHAR(45),
    DIRECCION VARCHAR(45),
    SEXO VARCHAR(45),
    EMAIL VARCHAR(45),
    CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (SK_DIM_CLIENTE)
);

CREATE TABLE SEGURO_DW_G26473741.DIM_EVALUACION_SERVICIO(
    SK_DIM_EVALUACION_SERVICIO INTEGER,
    COD_EVALUACION_SERVICIO INTEGER,
    NB_DESCRIP VARCHAR(25),
    CONSTRAINT PK_DIM_EVALUACION_SERVICIO PRIMARY KEY (SK_DIM_EVALUACION_SERVICIO)
);

CREATE TABLE SEGURO_DW_G26473741.DIM_CONTRATO(
    SK_DIM_CONTRATO INTEGER,
    NRO_CONTRATO INTEGER,
    DESCRIP_CONTRATO VARCHAR(25),
    CONSTRAINT PK_DIM_CONTRATO PRIMARY KEY (SK_DIM_CONTRATO)
);

CREATE TABLE SEGURO_DW_G26473741.DIM_ESTADO_CONTRATO(
    SK_DIM_ESTADO_CONTRATO INTEGER,
    COD_ESTADO INTEGER,
    DESCRIP_ESTADO VARCHAR(25),
    CONSTRAINT PK_DIM_ESTADO_CONTRATO PRIMARY KEY (SK_DIM_ESTADO_CONTRATO)
);

CREATE TABLE SEGURO_DW_G26473741.DIM_SINIESTRO(
    SK_DIM_SINIESTRO INTEGER,
    NRO_SINIESTRO INTEGER,
    DESCRIP_SINIESTRO VARCHAR(25),
    CONSTRAINT PK_DIM_SINIESTRO PRIMARY KEY (SK_DIM_SINIESTRO)
);

CREATE TABLE SEGURO_DW_G26473741.DIM_SUCURSAL(
    SK_DIM_SUCURSAL INTEGER,
    COD_SUCURSAL INTEGER,
    NB_SUCURSAL VARCHAR(25),
    COD_CIUDAD VARCHAR(45),
    NB_CIUDAD VARCHAR(45),
    COD_PAIS VARCHAR(45),
    NB_PAIS VARCHAR(45),
    CONSTRAINT PK_DIM_SUCURSAL PRIMARY KEY (SK_DIM_SUCURSAL)
);
--HECHOS

CREATE TABLE SEGURO_DW_G26473741.FACT_METAS(
    SK_DIM_FECHA_INICIO_META INTEGER,
    SK_DIM_PRODUCTO INTEGER,
    SK_DIM_FECHA_FIN_META INTEGER,
    MONTO_META_VENTA REAL,
    META_RENOVACION INTEGER,
    META_ASEGURADOS INTEGER,
    CONSTRAINT PK_FACT_METAS PRIMARY KEY (SK_DIM_FECHA_INICIO_META,SK_DIM_PRODUCTO,SK_DIM_FECHA_FIN_META),
    CONSTRAINT FK_DIM_FECHA_INICIO_META FOREIGN KEY (SK_DIM_FECHA_INICIO_META) REFERENCES SEGURO_DW_G26473741.DIM_TIEMPO (SK_DIM_TIEMPO),
    CONSTRAINT FK_DIM_FECHA_FIN_META FOREIGN KEY (SK_DIM_FECHA_FIN_META) REFERENCES SEGURO_DW_G26473741.DIM_TIEMPO (SK_DIM_TIEMPO),
    CONSTRAINT FK_DIM_PRODUCTO FOREIGN KEY (SK_DIM_PRODUCTO) REFERENCES SEGURO_DW_G26473741.DIM_PRODUCTO (SK_DIM_PRODUCTO)
);

CREATE TABLE SEGURO_DW_G26473741.FACT_EVALUACION_SERVICIO(
    SK_DIM_FECHA_RECOMIENDA INTEGER,
    SK_DIM_CLIENTE INTEGER,
    SK_DIM_PRODUCTO INTEGER,
    SK_DIM_EVALUACION_SERVICIO INTEGER,
    CANTIDAD INTEGER,
    RECOMIENDA_AMIGO INTEGER,
    CONSTRAINT PK_FACT_EVALUACION_SERVICIO PRIMARY KEY (SK_DIM_FECHA_RECOMIENDA,SK_DIM_CLIENTE,SK_DIM_PRODUCTO,SK_DIM_EVALUACION_SERVICIO),
    CONSTRAINT FK_DIM_FECHA_RECOMIENDA FOREIGN KEY (SK_DIM_FECHA_RECOMIENDA) REFERENCES SEGURO_DW_G26473741.DIM_TIEMPO (SK_DIM_TIEMPO),
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (SK_DIM_CLIENTE) REFERENCES SEGURO_DW_G26473741.DIM_CLIENTE (SK_DIM_CLIENTE),
    CONSTRAINT FK_DIM_PRODUCTO FOREIGN KEY (SK_DIM_PRODUCTO) REFERENCES SEGURO_DW_G26473741.DIM_PRODUCTO (SK_DIM_PRODUCTO),
    CONSTRAINT FK_DIM_EVALUACION_SERVICIO FOREIGN KEY (SK_DIM_EVALUACION_SERVICIO) REFERENCES SEGURO_DW_G26473741.DIM_EVALUACION_SERVICIO(SK_DIM_EVALUACION_SERVICIO)
);

CREATE TABLE SEGURO_DW_G26473741.FACT_REGISTRO_CONTRATO(
    SK_DIM_TIEMPO_FECHA_INICIO INTEGER,
    SK_DIM_TIEMPO_FECHA_FIN INTEGER,
    SK_DIM_CLIENTE INTEGER,
    SK_DIM_CONTRATO INTEGER,
    SK_DIM_PRODUCTO INTEGER,
    SK_DIM_ESTADO_CONTRATO INTEGER,
    MONTO REAL,
    CANTIDAD INTEGER,
    CANTIDAD_CLIENTE INTEGER,
    CANTIDAD_PRODUCTO INTEGER,
    CANTIDAD_CONTRATO INTEGER,
    CONSTRAINT PK_FACT_REGISTRO_CONTRATO PRIMARY KEY (SK_DIM_TIEMPO_FECHA_INICIO,SK_DIM_TIEMPO_FECHA_FIN, SK_DIM_CLIENTE, SK_DIM_CONTRATO, SK_DIM_PRODUCTO,SK_DIM_ESTADO_CONTRATO),
    CONSTRAINT FK_DIM_TIEMPO_FECHA_INICIO FOREIGN KEY (SK_DIM_TIEMPO_FECHA_INICIO) REFERENCES SEGURO_DW_G26473741.DIM_TIEMPO (SK_DIM_TIEMPO),
    CONSTRAINT FK_DIM_TIEMPO_FECHA_FIN FOREIGN KEY (SK_DIM_TIEMPO_FECHA_FIN) REFERENCES SEGURO_DW_G26473741.DIM_TIEMPO (SK_DIM_TIEMPO),
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (SK_DIM_CLIENTE) REFERENCES SEGURO_DW_G26473741.DIM_CLIENTE (SK_DIM_CLIENTE),
    CONSTRAINT FK_DIM_PRODUCTO FOREIGN KEY (SK_DIM_PRODUCTO) REFERENCES SEGURO_DW_G26473741.DIM_PRODUCTO (SK_DIM_PRODUCTO),
    CONSTRAINT FK_DIM_ESTADO_CONTRATO FOREIGN KEY (SK_DIM_ESTADO_CONTRATO) REFERENCES SEGURO_DW_G26473741.DIM_ESTADO_CONTRATO (SK_DIM_ESTADO_CONTRATO)
);

CREATE TABLE SEGURO_DW_G26473741.FACT_REGISTRO_SINIESTRO(
    SK_DIM_FECHA_SINIESTRO INTEGER,
    SK_DIM_FECHA_RESPUESTA INTEGER,
    SK_DIM_CLIENTE INTEGER,
    SK_DIM_SUCURSAL INTEGER,
    SK_DIM_CONTRATO INTEGER,
    SK_DIM_PRODUCTO INTEGER,
    SK_DIM_SINIESTRO INTEGER,
    CANTIDAD INTEGER,
    MONTO_RECONOCIDO REAL,
    MONTO_SOLICITADO REAL,
    ID_RECHAZO CHAR(2),
    CONSTRAINT PK_FACT_REGISTRO_SINIESTRO PRIMARY KEY (SK_DIM_FECHA_SINIESTRO, SK_DIM_FECHA_RESPUESTA, SK_DIM_CLIENTE, SK_DIM_SUCURSAL, SK_DIM_CONTRATO, SK_DIM_PRODUCTO, SK_DIM_SINIESTRO),
    CONSTRAINT FK_DIM_FECHA_SINIESTRO FOREIGN KEY (SK_DIM_FECHA_SINIESTRO) REFERENCES SEGURO_DW_G26473741.DIM_TIEMPO (SK_DIM_TIEMPO),
    CONSTRAINT FK_DIM_FECHA_RESPUESTA FOREIGN KEY (SK_DIM_FECHA_RESPUESTA) REFERENCES SEGURO_DW_G26473741.DIM_TIEMPO (SK_DIM_TIEMPO),
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (SK_DIM_CLIENTE) REFERENCES SEGURO_DW_G26473741.DIM_CLIENTE (SK_DIM_CLIENTE),
    CONSTRAINT FK_DIM_SUCURSAL FOREIGN KEY (SK_DIM_SUCURSAL) REFERENCES SEGURO_DW_G26473741.DIM_SUCURSAL (SK_DIM_SUCURSAL),
    CONSTRAINT FK_DIM_CONTRATO FOREIGN KEY (SK_DIM_CONTRATO) REFERENCES SEGURO_DW_G26473741.DIM_CONTRATO (SK_DIM_CONTRATO),
    CONSTRAINT FK_DIM_PRODUCTO FOREIGN KEY (SK_DIM_PRODUCTO) REFERENCES SEGURO_DW_G26473741.DIM_PRODUCTO (SK_DIM_PRODUCTO),
    CONSTRAINT FK_DIM_SINIESTRO FOREIGN KEY (SK_DIM_SINIESTRO) REFERENCES SEGURO_DW_G26473741.DIM_SINIESTRO (SK_DIM_SINIESTRO)
);